### ISSUE TITLE
老哥，能留个联系方式吗？想请教一个问题，我的内核代码会遭受攻击，被攻击后俱乐部服务连不上协调服务，但是没有DDOS或者CC攻击记录

### ISSUE THREAD

**Issue by xxTree** [0990/foxuc#2]
求一个联系方式！

**Comment by xxTree** [comment]
我的QQ是442860990

**Comment by xxTree** [comment]
可以付费咨询

**Comment by 0990** [comment]
你的内核用的哪个，官方？破解版？还是本项目的

**Comment by xxTree** [comment]
> 

项目是创胜买的，内核引擎有源码，服务核心没有源码，只有一个ServiceCore.dll，我用你的项目替换，但是会直接报错
![1651906298(1)](https://user-images.githubusercontent.com/32122937/167242609-145a6f86-ccd4-4f6c-be3a-c843306c89fe.png)

**Comment by 0990** [comment]
sorry,I cann't help if not this project
